### ISSUE TITLE
Wordpress?

### ISSUE THREAD

**Issue by jaycbrf4** [geedmo/yamm3#32]
How can this be incorporated with WordPress? Will the wp_navwalker.php have to be modified?

**Comment by mjrev** [comment]
@jaycbrf4 use something like @import url("../custom_path/yamm.css"); or insert [content of css](https://github.com/geedmo/yamm3/blob/master/yamm/yamm.css) directly in style.css

**Comment by geedmo** [comment]
Closed as this is not an issue with Yamm.
