### ISSUE TITLE
Add a opacity layer beneath the dropdown?

### ISSUE THREAD

**Issue by emage** [geedmo/yamm3#37]
I am using this as a mega menu layout to display shopping cart item.  My issue is that if the mega menu displays cart product and its over a list of similar product its hard to see whats in the mega menu and whats not -- it would be great to add a layer beneath it so i can set to black color of opacity 50% -- I guess similar to how modal is

This will help focus on the mega menu product item

any tips is appreciated

**Comment by geedmo** [comment]
I understand the usefulness of this but this is more a design necessity and imho is not really needed and I prefer to leave the component the more simple as possible.
Thanks
