### ISSUE TITLE
Menu pops up instantly

### ISSUE THREAD

**Issue by pjtfernandes** [geedmo/yamm3#38]
The menu drop downs comes up instantly when passing your mouse over it. Where can I add a css delay to it to make it look less jumpy?

**Comment by fotan** [comment]
Found this elsewhere...
```
<script>
	$('.dropdown').hover(function() {
	    $(this).find('.dropdown-menu').stop(true, true).delay(100).fadeIn(100);
	    }, function() {
	    $(this).find('.dropdown-menu').stop(true, true).delay(10).fadeOut(100);
	});
</script>
```
I think it's pretty straight forward?  Working well for me.
