### ISSUE TITLE
Full "Fluid" width on drop?

### ISSUE THREAD

**Issue by Hyp3rionM4x** [geedmo/yamm3#42]
Hi, im not sure if this is possible. But is is possible to make a "Fluid" design? Meaning instead of only use the same container width the damn menu uses, i would like the drop-menu to be 100% in width both ways... and then inside that perhaps make a container to center stuff and then from there work out the menu.

However if this IS possible? Would this destroy the mobile-responsive design?

Hope an answer soon.
Regards, Hyp3rion.

**Comment by geedmo** [comment]
Hi, do you have a screenshot or plunkr with some modifications to understand what you need? 
It seems the idea of a fluid design is like using .container-fluid instead of just .container, but in both cases the menu will switch to a collapsible element for mobiles.

**Comment by Hyp3rionM4x** [comment]
Hello, sorry for the delay i've had depression over the last year or so, so i've not been online as much as i would like to. Sorry about that.

The problem has been solved tho and working properly now, thanks for the idea and thanks for the support/help! :)

PS: Will be in contact if i have other ideas or need help for anything else. Thanks again! :)

**Comment by PrestaShark** [comment]
Hi Daniel!
Sad to hear about Your problems! I hope You are in good condition right now
and everything is ok.
Keep up a good work with Yamm and other stuff :)

Best regards from Poland!

2016-06-08 10:03 GMT+02:00 Daniel.P <notifications@github.com>:
