### ISSUE TITLE
Two menus in navbar-fixed-top - dropdown

### ISSUE THREAD

**Issue by Upioorny** [geedmo/yamm3#44]
Hello!
With two diffrent menus in static navbar dropdown showing and the and on the nav divs.

----- navbar ---
div > menu top-toolbar
## div > main menu

> dropdown shows here from booth menus<

Any tips?
Thx!

PS
The seme problem is when u put any paragraph or other div below menu

**Comment by geedmo** [comment]
Hello, could you elaborate this a bit more? It's not very clear what you've posted..
When you get a chance please also provide a demo on plunkr/jsbin to check
Thanks
