### ISSUE TITLE
Adding Multi level options

### ISSUE THREAD

**Issue by krugerdavid** [geedmo/yamm3#45]
Hi!
Great Mega Menu!!! It was very helpful!! BTW is there a chance to do multilevel menus on yamm? like this snipp? http://bootsnipp.com/snippets/featured/multi-level-navbar-menu

Regards

**Comment by geedmo** [comment]
Hi, I think multilevel menu could be placed in another micro repo like this. That would be better than bloating the code whit something that's optional.
Thanks, regards
