### ISSUE TITLE
Add to CDN for easy deployment on production environments

### ISSUE THREAD

**Issue by holtkamp** [geedmo/yamm3#46]
First of all, compliments for the library!

To deploy it on a production environment, hosting on a reliable CDN would be nice.
For the time being [RawGit](http://www.rawgit.com) suits fine, this converts a GitHub URL to a CDN like approach:
https://cdn.rawgit.com/geedmo/yamm3/master/yamm/yamm.css

But maybe you can consider registering it at something like www.cdnjs.com?

**Comment by holtkamp** [comment]
Shameless (and desperate?) bump on this? @geedmo would you consider opening up this project to the community so we can help a bit with managing it?

**Comment by geedmo** [comment]
Sorry for such a long delay. I think due to the very small size of the css involved it would be a better choice for production to inline the content. Anyway, I'll check the how to at cdnjs repo.

**Comment by geedmo** [comment]
CDN was available at https://cdn.rawgit.com/geedmo/yamm3/master/yamm/yamm.css
And since rawgit it shutting down, you can use from jsDelivr
https://cdn.jsdelivr.net/gh/geedmo/yamm3@master/yamm/yamm.css
