### ISSUE TITLE
Warning: dropdown menu appears on extreme left when used with SmartMenus plugin

### ISSUE THREAD

**Issue by holtkamp** [geedmo/yamm3#47]
[Bootstrap 3 dropped support for SubMenu's](http://stackoverflow.com/questions/18023493/bootstrap-3-dropdown-sub-menu-missing), so we adopted the [JQuery SmartMenus v1.0.0-beta1](http://www.smartmenus.org) plugin, which has a Bootstrap add-on. 

When experimenting with YAMM3, our dropdown menus kept appearing on the extreme left underneath the navbar, instead of directly under the clicked menu item. When disabling JQuery SmartMenus, this no longer occurred. 

It seems the SmartMenu [positions the dropdown menu dynamically](https://github.com/vadikom/smartmenus/blob/b00959d871413a9013a27b3792a8f683ee05b446/dist/jquery.smartmenus.js#L803), interfering with YAMM. 

Not sure whether the use of both plugins is possible; just submitting this issue so others can find it when their dropdown menu's keep on appearing on the extreme left :smile:

**Comment by geedmo** [comment]
Thanks for sharing this!
