### ISSUE TITLE
Bower Install Issue

### ISSUE THREAD

**Issue by Christopherallen** [geedmo/yamm3#48]
Running -

```
bower install yamm3 --save
```

This does not include the the yamm.styl or _yamm.scss file. Running it on a project with a few different machines and those seem to be the only files missing.

**Comment by chronon** [comment]
There has not been a tagged release since v1.1.0 so the commits adding those files are missing. @geedmo would a release be possible?

**Comment by chronon** [comment]
Alternatively, the `master` branch can be used by running `bower install yamm3#master`.

**Comment by geedmo** [comment]
Added some tags to fix this. The scss and styl files should be available at v1.2.0
