### ISSUE TITLE
How to set dropdown width to 100% (full width) 

### ISSUE THREAD

**Issue by forgetpluto** [geedmo/yamm3#51]
How to set dropdown width to 100% (full width)

**Comment by codethirteen** [comment]
It's in the demo. Add class `yamm-fw` to your dropdown list item.

```html
<nav class="navbar yamm navbar-default " role="navigation">
...
     <ul class="nav navbar-nav">
       <li class="dropdown yamm-fw">
             ...
       </li>
     </ul>
...
</nav>
```

**Comment by nick-jlsa** [comment]
This works to make the megamenu the full width of the container... but what you want it to be the full width of the browser window. I can't seem to get the code right. 

Can anyone offer some advice?

**Comment by nick-jlsa** [comment]
I have been comparing the CSS with this http://jsfiddle.net/mng9bhk8/ and I cannot figure out what the difference is. But this example does do what I want but I prefer to use YAMM3 if I can accomplish this effect.

**Comment by warudin** [comment]
I might be a bit late with an answer but it might also be of help for someone else. You can make the menu full width of the window, but you have to move the dropdown-menu out of the default container into another container-fluid. With a few extra CSS customizations you'll get there!

see: https://jsfiddle.net/DominiquePijnenburg/her4o2uf/
(make sure to make the preview window wide enough to see the full width effect)
