### ISSUE TITLE
Bower dependencies

### ISSUE THREAD

**Issue by RopoMen** [geedmo/yamm3#52]
Hi,

Is it necessary to add "bootstrap" as "dependencies" inside bower.json?

I'm using "bootstrap-sass", but because I have also added yamm3 inside bower I get also "bootstrap" (less version) included inside my bower_components folder. It just adds extra weight on bower install which is done inside CI (jenkins) after each build.

Also it is confusing to see "bootstrap" and "bootstrap-sass", because if you are new in the project you are not sure which is in use (unless search, but then you are confused that why that "bootstrap" is installed)

Also when you think about how yamm3 is used (at least from my perspective)
1. You choose your CSS framework what you start using in your project i.e. Bootstrap (less or sass or even plain css)
2. You then search additional components around it like yamm3, but in this point you already have installed your framework -> it is not needed to add "bootstrap" as dependency for yamm3.

Br,
Markku

**Comment by jdahdah** [comment]
This has been brought up [here](https://github.com/geedmo/yamm3/issues/34) before. Until the issue is fixed, you can add the following to your .bowerrc

```
 {
  "directory": "bower_components",
  "ignoredDependencies": [
    "bootstrap"
  ]
}
```

**Comment by geedmo** [comment]
Removed bootstrap from bower. I'll release v1.3 with latest changes. Sorry for the sooo lazy answer
