### ISSUE TITLE
yamm3 mega menu on button (without nav markup)

### ISSUE THREAD

**Issue by isteven** [geedmo/yamm3#53]
Hi geedmo,

Good job on the yamm3 library.

I need to show a mega menu on button click (not nav). Is there a way to use this mega menu on normal button?

Thanks.

**Comment by nikhilrajnair** [comment]
I am also trying to implement without nav, is there any possible way? i already have a nav-bar in my project . i want to use this as independent menu.

**Comment by geedmo** [comment]
This won't work as standalone  because it basically relies on changing some behaviors of bootstrap navbar specifically to allow more components. 
Thank you both for your feedback.
