### ISSUE TITLE
need_demo? Here is a starting point...

### ISSUE THREAD

**Issue by pmorch** [geedmo/yamm3#54]
I see that for many reported issues, one is asked to provide an online demo and the issue is tagged with need_demo.

I looked for some time for a online-demo starting point that worked, but couldn't find one. So I created one: http://www.codeply.com/go/jVTHOklGaY

(It is basically a cut'n'paste of http://geedmo.github.io/yamm3/)

I'd like to ask that this (or some other) starting point be linked to from the main page, so that beginners have something to fiddle with...

**Comment by geedmo** [comment]
I will add somehing like or by checking other popular repositories for common practices to add new issue. I know this repo is prett simple but as you mention it will help a lot to have a minimum set of guidelines. I'll evaluate future issues if necessary will add it. Thank you so much for your contribution.

**Comment by geedmo** [comment]
I've added some guidelines and issue template to help to report bug and request features.
https://github.com/geedmo/yamm3/blob/master/.github/CONTRIBUTING.md

Thanks!
