### ISSUE TITLE
Bootstrap 4 (alpha 2) works!

### ISSUE THREAD

**Issue by pmorch** [geedmo/yamm3#55]
I'd like to just let people know that it works out of the box with Bootstrap 4 also.

Here is a demo: http://www.codeply.com/go/2AAeoskq4B

Note that the nav bar markup is somewhat different between Bootstrap 3 and 4, so one can't just take a Bootstrap 3 YAMM3 demo and use Bootstrap 4 with it, but that isn't because of YAMM3. (It wasn't for me, anyway).

Perhaps you want to mention that to people starting up with Bootstrap 4. Or just feel free to close this bug with no action.

**Comment by psorensen** [comment]
confirming this works on alpha 5

**Comment by SRTM** [comment]
Doesn't work with Beta 2 :(

**Comment by jpdupont** [comment]
Possible to update the codeply demo to Bootstrap 4 beta3 ??? Thanks !

**Comment by geedmo** [comment]
#63
