### ISSUE TITLE
force mega menu to mobile on all mobile devices

### ISSUE THREAD

**Issue by kyoukhana** [geedmo/yamm3#57]
I haven't found any code to force the mega menu to mobile on all mobile devices.  Including the iPad.  The mega menu doesn't look great on the iPad.

**Comment by geedmo** [comment]
The menu collapses itself due to Bootstrap reponsive classes. It doesn't do anything special because what needs to be customized is the custom added content, indeed, the online demo has some few media queries to achieve that customization.
