### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by kyoukhana** [geedmo/yamm3#60]
Was wondering if this project is dead and is there alternative

**Comment by slolo2000** [comment]
Same question here, if someone has information about the future of the project.

Thanks in advance and have a nice day.

**Comment by lenin-interware** [comment]
It seems that the project is no longer maintained. It's a shame, a lot of people use it.

**Comment by eduardomart** [comment]
Someone should fork it :-)

**Comment by geedmo** [comment]
https://github.com/geedmo/yamm3/issues/63#issuecomment-489649895
