### ISSUE TITLE
Megamenu longer than page on mobile

### ISSUE THREAD

**Issue by ImTheKeyMaster** [geedmo/yamm3#64]
Hi,
When the megamenu is opened on a mobile device, it is sometimes longer than the actual page.  Because of this, the page will not scroll to show all of the menu choices.  Have you run into this and is there a simple fix?  Thanks!

**Comment by geedmo** [comment]
You can try limiting the navbar height with 'max-height' for example. Anyway, it should not affect the scrolling of the page, at most, you will end up with two scrollbar (page and menu) and the navbar will cover the page if the set as fixed. Feel free to repopen with a code demo to evaluate in detail.
