### ISSUE TITLE
Publishing on npm

### ISSUE THREAD

**Issue by Tilogorn** [geedmo/yamm3#67]
I'm happy to see that you decided to maintain this great package again! Thank you! Would you mind publishing your package on npm as it is the most famous alternative to bower and the guys at bower are trying to put it slowly out of service? 

I'm just trying to get rid of bower but this dependency prevents me from doing it completely.

**Comment by geedmo** [comment]
Sure! I've been doing changes to publish to npm so I think in the next hours it should be available.

**Comment by geedmo** [comment]
Now you can intall with: `npm install @geedmo/yamm3 --save`
Thanks for supporting this project!
