### ISSUE TITLE
Issue facing  in yamm3 mega menu height 

### ISSUE THREAD

**Issue by priyahG** [geedmo/yamm3#68]
Hi Guys

Have a navigation bar with one yamm mega menu, some times it's loaded partial height for mega menu , i will attach the screenshot for reference. In rare case only, these issue persists, I want to know, when the height atomatically sets for megamenu-col (class) division tag, for eg., <div _ngcontent-c3="" class="col-sm-3 megamenu-col" style="height: 152px;">, here height loaded automatically, how it's loaded? else give any better solution to avoid this issue
![issue](https://user-images.githubusercontent.com/50356361/57281204-1c2d1f00-70c8-11e9-99e3-922e341f71ff.JPG)
![actual menu](https://user-images.githubusercontent.com/50356361/57281240-3666fd00-70c8-11e9-9804-64350d5926fe.JPG)
![rendered html for actual menu](https://user-images.githubusercontent.com/50356361/57281300-54346200-70c8-11e9-9ca6-8847b98b5709.JPG)
![rendered html for issue menu](https://user-images.githubusercontent.com/50356361/57281332-67473200-70c8-11e9-93bf-d06e2feab79b.JPG)

**Comment by geedmo** [comment]
Hi, there's no code that forces the height of menus. The menus take the height based on the content, in the same way like a standard dropdown works. I think it could be something with the markup perhaps, but hard to say, just in case try validating your html. 
Otherwise please provide a reproducible case to check.

**Comment by priyahG** [comment]
Hi

Thanks for supporting. Rare cases only it's reproduced,  like for eg.,if application is idle for more than 10 minutes it's reproduced.

All the menu contents showing in rendered html page (inspect element). When page loading , at the time, height is not setting for megamenu-col div tag. If app idle, if I click other menu like police alert and try to click services menu , issue reproduced.

Then , on page load hover not working,  if site idle  then trying to click menu, hover working,  height also mismatched. If I refresh the screen , I will not get the issue.

NOTE: when I remove the class .dropdown-menu , content showing fully in inspect element. But ui is not aligned properly.

Thanks
Priya

Get Outlook for Android<https://aka.ms/ghei36>




On Wed, May 8, 2019 at 3:43 AM +0530, "geedmo" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, there's no code that forces the height of menus. The menus take the height based on the content, in the same way like a standard dropdown works. I think it could be something with the markup perhaps, but hard to say, just in case try validating your html.
Otherwise please provide a reproducible case to check.

-

**Comment by geedmo** [comment]
Unfrotunately I can't say too much just seeing those screenshots,:
To help track and check issues I've added some guidelines to organize new issues reports: https://github.com/geedmo/yamm3/blob/master/.github/CONTRIBUTING.md
When you get a chance please try to create a reproducible test case. There's another similar issue reported but no demo so I can't find a way to replicate and check where could be the problem.
