### ISSUE TITLE
yamm3 dropdown mega menu issue in iOS devices(version-12.2)

### ISSUE THREAD

**Issue by prasanna1579** [geedmo/yamm3#69]
Hi Team,

We are supporting a public website(www.unitywater.com) which was implemented using Sitecore 8.2 and .Net MVC. We have used bootstrap yamm3 dropdown for mega menu in our project and recently after upgrading the iOS version to 12.2, we are having a problem with mega menu in iOS devices.
 
After clicking on Mega menu, the sub menu items are displaying properly, But if we click on any of the sub menu item, the child items are rendering behind the home page banner image and overlapping with the content text. This is happening on first click. If we click on same link second time, the dropdown menu renders fine. If we click on same link third time, the dropdown hides, but the background still shows the overlapping text and child menu items.

Attached the screen shots taken from my production public website for reference.

Note: This is working fine in Android devices. Only issue with iOS devices in both Safari and Chrome browser.

As this is a high priority issue and client is looking for faster resolution, can you please look into this issue asap?

Please let me know if you need any further information.

![file](https://user-images.githubusercontent.com/50469768/57496980-59292980-72f3-11e9-826c-1f82f8459872.png)
![file1](https://user-images.githubusercontent.com/50469768/57496981-59c1c000-72f3-11e9-8e85-a6837ea472e4.png)
![file2](https://user-images.githubusercontent.com/50469768/57496982-59c1c000-72f3-11e9-9c85-2ddb31e8d14d.png)
![file3](https://user-images.githubusercontent.com/50469768/57496983-59c1c000-72f3-11e9-8041-b138cf2ad903.png)
![file-1](https://user-images.githubusercontent.com/50469768/57497232-77435980-72f4-11e9-9a6e-644d7dd72eb6.png)

Thank you,
Lakshmana Prasanna Kumar

**Comment by geedmo** [comment]
Hi, unfrotunately I can't say too much just seeing those screenshots,:
To help track and check issues I've added some guidelines to organize new issues reports: https://github.com/geedmo/yamm3/blob/master/.github/CONTRIBUTING.md
When you get a chance please try to create a reproducible test case. There's another similar issue reported but no demo so I can't find a way to replicate and check where could be the problem.

Btw, I've checkd the demo on an iphone with ios 12.2 and no render issues.
