### ISSUE TITLE
Can't click on submenu items

### ISSUE THREAD

**Issue by N6REJ** [geedmo/yamm3#71]
I'm having a problem where yamm is closing so fast I can't click on children in submenu's.
This is with Joomla 3.9.13, bootstrap 3.4.1
Without yamm this didn't happen.
I've shown in the video the steps I've taken to solve the issue.

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
Windows 10 x64 pro

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Firefox 71.0b12 ( 64bit)

I've only added yamm as shown here and included the .scss in my master build
![image](https://user-images.githubusercontent.com/1850089/70034605-0e188180-1577-11ea-82b3-85d1f17bfb04.png)

[Here's a short video documenting the issue.](https://youtu.be/cXuS3Al5Z2I)

**Comment by geedmo** [comment]
Hi, I can't determine exactly the cause without a reproducible case and also since bootstrap 3 doesn't support submenu items on dropdowns there's more involved than just adding yamm.

**Comment by N6REJ** [comment]
afaik bs3 support 2 deep subs?

**Comment by geedmo** [comment]
Not really, please see here https://github.com/twbs/bootstrap/issues/14944
I appreciate you take the time to provide details and a video, but I need something I can check without trying to guess what could be firing this issue.

**Comment by N6REJ** [comment]
ty @geedmo   By moving the sub menu tab higher ( top: 0; ) I was then able to click on it.  It was not related to yamm after all.
I apologize my info wasn't adequate.
